// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjIyoPtqv58C_XjodoeYkN6yYQEmNi2NU',
    appId: '1:680576577106:web:3c93ab7877f72468c0798b',
    messagingSenderId: '680576577106',
    projectId: 'pushnotification-5cd6b',
    authDomain: 'pushnotification-5cd6b.firebaseapp.com',
    storageBucket: 'pushnotification-5cd6b.appspot.com',
    measurementId: 'G-X7ZYFEEQLH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbsdUxqtRJPKWVkYTrEzE17ukfRxZ0GlQ',
    appId: '1:680576577106:android:be75d8c76f75d092c0798b',
    messagingSenderId: '680576577106',
    projectId: 'pushnotification-5cd6b',
    storageBucket: 'pushnotification-5cd6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApJ8ZArePIi4j_aNBQrZS_B0PJ5oCZjDE',
    appId: '1:680576577106:ios:59452dc89e4cd9c1c0798b',
    messagingSenderId: '680576577106',
    projectId: 'pushnotification-5cd6b',
    storageBucket: 'pushnotification-5cd6b.appspot.com',
    iosClientId: '680576577106-codqq1uvit8j2nit85kcctcjkfsp6s8l.apps.googleusercontent.com',
    iosBundleId: 'com.example.instaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApJ8ZArePIi4j_aNBQrZS_B0PJ5oCZjDE',
    appId: '1:680576577106:ios:8aff6005461f0ba4c0798b',
    messagingSenderId: '680576577106',
    projectId: 'pushnotification-5cd6b',
    storageBucket: 'pushnotification-5cd6b.appspot.com',
    iosClientId: '680576577106-4prvbkck21mifoj8luucrgefdfclt1vi.apps.googleusercontent.com',
    iosBundleId: 'com.example.instaApp.RunnerTests',
  );
}
